# Database Configuration
spring.application.name=devmonitor
spring.datasource.url=jdbc:postgresql://localhost:5432/devmonitor
spring.datasource.username=postgres
spring.datasource.password=Lapaix@123
#spring.datasource.username=${DB_USERNAME:devmonitor}
#spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# JWT Configuration
app.jwtSecret=${JWT_SECRET:mySecretKey}
app.jwtExpirationMs=86400000

# Logging Configuration
logging.level.rw.gradtechgroup.devmonitor=DEBUG
logging.level.org.springframework.security=DEBUG

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method